const mongoose = require('mongoose');

const freightDataSchema = new mongoose.Schema({
  "Transport Mode": { type: String, required: true, trim: true },
  "Direction": { type: String, required: true, trim: true },
  "ETD Date": { type: Date },
  "ETA Date": { type: Date },
  "Changed ETD": { type: String, trim: true },
  "Changed ETA": { type: String, trim: true },
  "Departure Region": { type: String, trim: true },
  "Departure Country Name": { type: String, trim: true },
  "Place of Receipt": { type: String, trim: true },
  "Place of Receipt Name": { type: String, trim: true },
  "Departure Port": { type: String, trim: true },
  "Departure Port Name": { type: String, trim: true },
  "Destination Corp Region": { type: String, trim: true },
  "Destination Corp Region Name": { type: String, trim: true },
  "Destination Country": { type: String, trim: true },
  "Destination Country Name": { type: String, trim: true },
  "Destination Port": { type: String, trim: true },
  "Destination Port Name": { type: String, trim: true },
  "Place of Delivery": { type: String, trim: true },
  "Place of Delivery Name": { type: String, trim: true },
  "Project ID": { type: String, trim: true },
  "STT": { type: String, trim: true },
  "MAWB/MBL": { type: String, trim: true },
  "HAWB/HBL": { type: String, trim: true },
  "Shipment Type": { type: String, trim: true },
  "DGR": { type: String, trim: true },
  "Incoterms": { type: String, trim: true },
  "Shipper Refs (SRS)": { type: String, trim: true },
  "Commercial Invoice (CIN)": { type: String, trim: true },
  "Purchase Order (PON)": { type: String, trim: true },
  "Sales Order (SON)": { type: String, trim: true },
  "Shipper Name & Address": { type: String, trim: true },
  "Consignee Name & Address": { type: String, trim: true },
  "Pieces": { type: Number },
  "Gross Weight": { type: Number },
  "Chargeable Weight": { type: Number },
  "Volume (CBM)": { type: Number },
  "Total Container TEU": { type: String, trim: true },
  "Container 20ft Count": { type: String, trim: true },
  "Container 40ft Count": { type: String, trim: true },
  "Container Number": { type: String, trim: true },
  "Container Seal Number": { type: String, trim: true },
  "Carrier": { type: String, trim: true },
  "Flight1/Vessel": { type: String, trim: true },
  "Flight2/Voyage": { type: String, trim: true },
  "Service Level": { type: String, trim: true },
  "Service Level Name": { type: String, trim: true },
  "Service Type": { type: String, trim: true },
  "Service Type Name": { type: String, trim: true },
  "Customer Booking (CBK)": { type: Date },
  "Pick UP from Customer (PUP)": { type: Date },
  "Receive @ Export Whse (REW)": { type: Date },
  "Booked on Flight/Vessel (BKD)": { type: Date },
  "Export Customs Cleared (ECD)": { type: Date },
  "Depart from Origin Port (DEP)": { type: Date },
  "Arrive At Destination Port (ARR)": { type: Date },
  "Consignee/Agent Informed of Arrival (NFD)": { type: Date },
  "Receive @ Import Whse (RIW)": { type: Date },
  "Documents Release to Broker (DRB/DTA/HDP)": { type: String, trim: true },
  "Cargo Cleared by Customs (CCD)": { type: String, trim: true },
  "First Self Collection by Consignee (SPC)": { type: String, trim: true },
  "Proof Of Delivery (POD)": { type: String },
}, {collection: 'freightData', timestamps: true });

module.exports = mongoose.model('FreightData', freightDataSchema);


